name: Deploy JouCode Dev

on:
  push:
    branches: [ "main" ]
jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Stop and remove container
      run: docker stop joucode_dev && docker rm joucode_dev || true
    - name: Remove Docker image
      run: docker rmi -f joucode_dev || true
    - name: Run docker-compose
      run: docker compose -f docker-compose.yml up -d